'picocalc-template.bas

OPTION GUI CONTROLS 5

Const BLK=RGB(BLACK)
Const BLU=RGB(BLUE)
Const CYN=RGB(CYAN)
Const GRN=RGB(GREEN)
Const RED=RGB(RED)
Const WHT=RGB(WHITE)
Const YLW=RGB(YELLOW)

GUI DELETE ALL
Font 1
Colour WHT,BLU
CLS BLU

GUI FRAME #1, "Home", 5, 5, 310, 310, WHT